apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp1
  labels:
    app: mywebapp1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mywebapp1
  template:
    metadata:
      labels:
        app: mywebapp1
    spec:
      containers:
      - name: mywebapp1
        image: poornimaasundkar/python_mywebapp1
        ports:
        - containerPort: 5000
